### ISSUE TITLE
Bug: Duplicate Entries in Books

### ISSUE THREAD

**Issue by Circuitbree** [rockerle/KanyQuoter#3]
Books sometimes contain the same quotes multiple times.

Screenshots:
![duplicate1](https://user-images.githubusercontent.com/88826332/129202036-6002ef02-bdbb-4f83-ba47-55ab625dffd4.PNG)
![duplicate2](https://user-images.githubusercontent.com/88826332/129202040-bc04d888-d185-48ad-9376-52a4cd55305e.PNG)

**Comment by rockerle** [comment]
filter to garantee unique quotes was implemented
