### ISSUE TITLE
Feature Request: Custom Amount of Quotes in a Book

### ISSUE THREAD

**Issue by Circuitbree** [rockerle/KanyQuoter#4]
An interesting addition to this mod would be the possibility to change the amount of qoutes, which are written in one book.

For example change the command from:

`.kanye`

to:

`.kanye x`

Where `x` is some number between 1 and a maximum amount of quotes (e.g. 50). In addition, error handling must be performed to resolve invalid inputs.

**Comment by rockerle** [comment]
Feature is implemented in version 1.1
