### ISSUE TITLE
Performance Optimization: Load Quotes on Game Start to Reduce Lag when Filling a Book

### ISSUE THREAD

**Issue by Circuitbree** [rockerle/KanyQuoter#5]
The moment the `.kanye` command is sent in chat the game freezes for a bit. This is most likely due to loading the quotes from the kanye API at the time when the chat message is sent. 

A possible Improvement would be to load a set amount of qoutes (e.g. the maximum number of qoutes which can be displayed, hint: #4) when starting the game and fabric loader loads the mod. Therefore a short lag would only occur during startup and would not affect the general performance of the game.

**Comment by rockerle** [comment]
Fixed with commit c060514

I put the grabbing of the quotes into a background process.
